server {
  listen 43100;
  server_name _;

  client_max_body_size 12m;
  proxy_connect_timeout 10s;
  proxy_read_timeout 180s;

  location / {
    proxy_pass http://api:43100;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
